- name: Create Loki directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ loki_data_dir }}"
    - "{{ loki_data_dir }}/data"

- name: Create Loki subdirectories
  file:
    path: "{{ item }}"
    state: directory
    owner: 10001
    group: 10001
  loop:
    - "{{ loki_data_dir }}/data"
    - "{{ loki_data_dir }}/data/index"
    - "{{ loki_data_dir }}/data/cache"
    - "{{ loki_data_dir }}/data/compactor"
    - "{{ loki_data_dir }}/data/chunks"
    - "{{ loki_data_dir }}/data/wal"

- name: Fix permissions for Loki
  file:
    path: "{{ loki_data_dir }}"
    state: directory
    recurse: yes
    owner: 10001
    group: 10001

- name: Template Loki config
  template:
    src: loki-config.yml.j2
    dest: "{{ loki_data_dir }}/loki-config.yml"

- name: Run Loki container
  community.docker.docker_container:
    name: loki
    image: "grafana/loki:{{ loki_version }}"
    state: started
    restart_policy: always
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "{{ loki_port }}:3100"
    volumes:
      - "{{ loki_data_dir }}/loki-config.yml:/etc/loki/local-config.yaml"
      - "{{ loki_data_dir }}/data:/loki"
    networks:
      - name: "{{ monitoring_docker_network }}"
