---
- name: Create Loki directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: 10001
    group: 10001
    mode: "0755"
  loop:
    - "{{ monitoring_loki_data_dir }}"
    - "{{ monitoring_loki_data_dir }}/data"

- name: Create Loki subdirectories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: 10001
    group: 10001
    mode: "0755"
  loop:
    - "{{ monitoring_loki_data_dir }}/data"
    - "{{ monitoring_loki_data_dir }}/data/index"
    - "{{ monitoring_loki_data_dir }}/data/cache"
    - "{{ monitoring_loki_data_dir }}/data/compactor"
    - "{{ monitoring_loki_data_dir }}/data/chunks"
    - "{{ monitoring_loki_data_dir }}/data/wal"

- name: Template Loki config
  ansible.builtin.template:
    src: loki-config.yml.j2
    dest: "{{ monitoring_loki_data_dir }}/loki-config.yml"
    mode: "0644"

- name: Run Loki container
  community.docker.docker_container:
    name: loki
    image: grafana/loki:{{ monitoring_loki_version }}
    state: started
    restart_policy: always
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "{{ monitoring_loki_port }}:3100"
    volumes:
      - "{{ monitoring_loki_data_dir }}/loki-config.yml:/etc/loki/local-config.yaml"
      - "{{ monitoring_loki_data_dir }}/data:/loki"
    networks:
      - name: "{{ monitoring_docker_network }}"
