---
app_name: bulletin-board

docker_image: "ghcr.io/dobro10k2/project-devops-deploy:{{ docker_tag | default('latest') }}"

docker_network_name: bulletin-network

app_port: 8080
management_port: 9090

app_logs_dir: /opt/bulletin/logs

postgres_container_name: postgres
postgres_db: bulletins
postgres_user: postgres
postgres_data_dir: /opt/postgres/data

spring_datasource_url: "jdbc:postgresql://{{ postgres_container_name }}:5432/{{ postgres_db }}"

env_vars:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_DATASOURCE_URL: "{{ spring_datasource_url }}"
  SPRING_DATASOURCE_USERNAME: "{{ postgres_user }}"
  MANAGEMENT_SERVER_PORT: "{{ management_port | string }}"
  JAVA_OPTS: "-Xms256m -Xmx512m"

minio_container_name: minio
minio_data_dir: /opt/minio/data

minio_console_port: 9001
minio_api_port: 9000

monitoring_server_ip: "{{ hostvars[groups['monitoring'][0]]['internal_ip'] }}"

app_server_ip: "{{ hostvars[groups['app'][0]]['internal_ip'] }}"

prometheus_targets:
  node_exporter:
    - "{{ app_server_ip }}:9100"
    - "{{ monitoring_server_ip }}:9100"

  application:
    - "{{ app_server_ip }}:9090"

  nginx:
    - "nginx-exporter:9113"

nginx_status_url: "http://{{ app_server_ip }}/nginx_status"

private_network_cidr: "10.129.0.0/24"

storage_s3:
  bucket: "bulletins"
  region: "us-east-1"
  endpoint: "http://minio:9000"
  cdn_url: "http://board.dobro10k2.ru/storage"

loki_port: 3100
loki_push_url: "http://{{ monitoring_server_ip }}:{{ loki_port }}/loki/api/v1/push"

vault_env_vars:
  SPRING_DATASOURCE_PASSWORD: "{{ vault_postgres_password }}"
  STORAGE_S3_BUCKET: "{{ storage_s3.bucket }}"
  STORAGE_S3_REGION: "{{ storage_s3.region }}"
  STORAGE_S3_ENDPOINT: "{{ storage_s3.endpoint }}"
  STORAGE_S3_ACCESSKEY: "{{ vault_minio_access_key }}"
  STORAGE_S3_SECRETKEY: "{{ vault_minio_secret_key }}"
  STORAGE_S3_CDNURL: "{{ storage_s3.cdn_url }}"
