---
app_name: bulletin-board

docker_image: ghcr.io/dobro10k2/project-devops-deploy

docker_network_name: bulletin-network

app_port: 8080
management_port: 9090

app_logs_dir: /opt/bulletin/logs

postgres_container_name: postgres
postgres_db: bulletins
postgres_user: postgres
postgres_data_dir: /opt/postgres/data

spring_datasource_url: jdbc:postgresql://postgres:5432/bulletins

env_vars:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_DATASOURCE_URL: "{{ spring_datasource_url }}"
  SPRING_DATASOURCE_USERNAME: "{{ postgres_user }}"
  MANAGEMENT_SERVER_PORT: "{{ management_port | string }}"
  JAVA_OPTS: "-Xms256m -Xmx512m"

minio_container_name: minio
minio_data_dir: /opt/minio/data

minio_console_port: 9001
minio_api_port: 9000

prometheus_targets:

  node_exporter:
    - "10.129.0.16:9100"

  application:
    - "10.129.0.16:9090"

  nginx:
    - "nginx-exporter:9113"

monitoring_server_ip: 10.129.0.25

nginx_status_url: "http://10.129.0.16/nginx_status"

private_network_cidr: "10.129.0.0/24"
