---
app_name: bulletin-board

docker_image: ghcr.io/dobro10k2/project-devops-deploy

docker_network_name: bulletin-network

app_port: 8080
management_port: 9090

app_logs_dir: /opt/bulletin/logs

monitoring_server_ip: "{{ hostvars[groups['monitoring'][0]]['internal_ip'] }}"

app_server_ip: "{{ hostvars[groups['app'][0]]['internal_ip'] }}"

prometheus_targets:
  node_exporter:
    - "{{ app_server_ip }}:9100"

  application:
    - "{{ app_server_ip }}:9090"

  nginx:
    - nginx-exporter:9113

nginx_status_url: http://{{ app_server_ip }}/nginx_status

private_network_cidr: 10.129.0.0/24

loki_port: 3100
loki_push_url: http://{{ monitoring_server_ip }}:{{ loki_port }}/loki/api/v1/push

# --- Runtime ---
promtail_runtime_mode: "root"
promtail_positions_path: "/var/lib/promtail"

# --- Loki client (REQUIRED) ---
promtail_clients:
  - url: "http://{{ monitoring_server_ip }}:3100/loki/api/v1/push"

# --- Scrape configs ---
promtail_scrape_configs:

  # =========================
  # NGINX
  # =========================
  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          app: nginx
          env: prod
          host: "{{ inventory_hostname }}"
          __path__: /var/log/nginx/*.log

    pipeline_stages:
      - json:
          expressions:
            time: time
            remote_addr: remote_addr
            method: method
            uri: uri
            status: status

  # =========================
  # APP
  # =========================
  - job_name: app
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:

      - source_labels: ['__meta_docker_container_name']
        regex: '/bulletin-board'
        action: keep

      - source_labels: ['__meta_docker_container_name']
        target_label: container

      - target_label: job
        replacement: app

      - target_label: app
        replacement: bulletin-board

      - target_label: env
        replacement: prod

      - target_label: host
        replacement: "{{ inventory_hostname }}"
