{
 "title": "Nginx Metrics",
 "tags": [ "nginx" ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "nginx_connections_active" }
   ]
  },
  {
   "title": "Reading",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "nginx_connections_reading" }
   ]
  },
  {
   "title": "Writing",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "nginx_connections_writing" }
   ]
  },
  {
   "title": "Waiting",
   "type": "stat",
   "gridPos": { "x": 18, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "nginx_connections_waiting" }
   ]
  },
  {
   "title": "Requests Per Second (RPS)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 4, "w": 12, "h": 8 },
   "targets": [
    { "expr": "nginx_http_requests_total" }
   ]
  }
 ]
}