- name: restart prometheus
  community.docker.docker_container:
    name: prometheus
    state: started
    restart: true

- name: restart grafana
  community.docker.docker_container:
    name: grafana
    state: started
    restart: true
