---
- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Allow required ports
  ufw:
    rule: allow
    port: "{{ item }}"
  loop: "{{ firewall_allowed_ports }}"

- name: Enable firewall
  community.general.ufw:
    state: enabled
