---
- name: Configure server
  hosts: servers
  roles:
    - docker_setup
    - firewall
    - docker_network
    - postgres
    - minio
    - nginx
    - certbot
    - node_exporter

- name: Deploy application
  hosts: servers
  roles:
    - role: docker_deploy
      tags: deploy
