---
- name: Configure server
  hosts: app
  roles:
    - docker_setup
    - firewall
    - docker_network
    - postgres
    - minio
    - nginx
    - certbot
    - node_exporter

- name: Deploy application
  hosts: app
  roles:
    - role: docker_deploy
      tags: deploy

- hosts: monitoring
  become: true

  roles:
    - firewall
    - docker_setup
    - prometheus
