- name: Configure application server
  hosts: app
  roles:
    - docker_setup
    - firewall
    - docker_network
    - nginx
    - certbot
    - role: prometheus.prometheus.node_exporter
      vars:
        node_exporter_web_listen_address: "0.0.0.0:9100"
    - role: grafana.grafana.promtail

- name: Setup monitoring server
  hosts: monitoring
  become: true
  roles:
    - firewall
    - docker_setup
    - monitoring
