---
- name: Create MinIO data directory
  ansible.builtin.file:
    path: "{{ minio_data_dir }}"
    state: directory
    owner: dobro10k2
    group: docker
    mode: "0755"

- name: Run MinIO container
  community.docker.docker_container:
    name: "{{ minio_container_name }}"
    image: minio/minio:latest
    state: started
    restart_policy: always

    command: server /data --console-address ":9001"

    env:
      MINIO_ROOT_USER: "{{ vault_env_vars.STORAGE_S3_ACCESSKEY }}"
      MINIO_ROOT_PASSWORD: "{{ vault_env_vars.STORAGE_S3_SECRETKEY }}"

    volumes:
      - "{{ minio_data_dir }}:/data"

    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - minio
          - bulletins.minio

    ports:
      - 127.0.0.1:9000:9000
      - 127.0.0.1:9001:9001

    recreate: false
    pull: false

- name: Wait for MinIO API
  ansible.builtin.uri:
    url: http://127.0.0.1:9000/minio/health/live
    method: GET
    status_code: 200
  register: minio_health
  retries: 10
  delay: 3
  until: minio_health.status == 200

- name: Check if mc alias exists
  ansible.builtin.command: >
    docker exec {{ minio_container_name }} mc alias list
  register: minio_mc_alias_list
  changed_when: false

- name: Configure mc alias
  ansible.builtin.command: >
    docker exec {{ minio_container_name }}
    mc alias set local http://127.0.0.1:9000
    {{ vault_env_vars.STORAGE_S3_ACCESSKEY }}
    {{ vault_env_vars.STORAGE_S3_SECRETKEY }}
  when: "'local' not in minio_mc_alias_list.stdout"
  changed_when: true

- name: Check if bucket exists
  ansible.builtin.command: >
    docker exec {{ minio_container_name }}
    mc ls local/{{ vault_env_vars.STORAGE_S3_BUCKET }}
  register: minio_bucket_check
  failed_when: false
  changed_when: false

- name: Create bucket
  ansible.builtin.command: >
    docker exec {{ minio_container_name }}
    mc mb local/{{ vault_env_vars.STORAGE_S3_BUCKET }}
  when: minio_bucket_check.rc != 0
  changed_when: false

- name: Set bucket public policy
  ansible.builtin.command: >
    docker exec {{ minio_container_name }}
    mc anonymous set download local/{{ vault_env_vars.STORAGE_S3_BUCKET }}
  changed_when: false
